import type { KnowledgeSeed } from "./seed-data";

const root = "local-source://summer-internship-autumn-recruitment/";

function localEntry(input: Omit<KnowledgeSeed, "slug" | "researchRound"> & { slug: string }): KnowledgeSeed {
  return { ...input, slug: `local-${input.slug}`, researchRound: 3 };
}

function make(
  slug: string, domain: KnowledgeSeed["domain"], category: string,
  titleZh: string, titleEn: string, summaryZh: string, summaryEn: string,
  contentZh: string, contentEn: string, keywords: string[],
  sourceTitle: string, sourcePath: string
) {
  return localEntry({
    slug, domain, category, titleZh, titleEn, summaryZh, summaryEn,
    contentZh, contentEn, keywords, competencies: [category],
    sourceTitle, sourceUrl: `${root}${encodeURIComponent(sourcePath)}`
  });
}

export const summerRecruitKnowledge: KnowledgeSeed[] = [
  make("ib-answer-60-90-100", "INVESTMENT_BANKING", "本地资料·投行面试",
    "投行面试的60/90/100分回答层级", "60/90/100-point investment-banking answers",
    "合格回答给出定义和结论，优秀回答增加推导与例子，顶级回答进一步加入交易场景、风险、反事实和追问预判。",
    "A passable answer gives definitions and conclusions; a strong one adds logic and examples; an exceptional one adds deal context, risks, counterfactuals, and anticipated follow-ups.",
    "回答先给结论，再给2至3层结构；技术题必须说明口径和假设，业务题要落到交易影响，开放题需主动指出信息不足和验证方法。",
    "Lead with the conclusion and use two or three layers. Technical answers state definitions and assumptions, business answers connect to deal impact, and open questions identify missing information and validation.",
    ["投行面试", "答题框架", "technical interview", "structured answer"],
    "面试知识库_KNOWLEDGE_BASE.md", "金融方向/面试知识库_KNOWLEDGE_BASE.md"),
  make("ib-comps-selection", "INVESTMENT_BANKING", "本地资料·估值实操",
    "可比公司筛选与口径统一", "Comparable-company selection and normalization",
    "可比公司不是简单找同行，而是比较业务结构、收入驱动、客户、地域、成长性、利润率和风险。",
    "Comparable companies require alignment on business mix, revenue drivers, customers, geography, growth, margins, and risk rather than merely sharing an industry label.",
    "先建立宽口径候选池，再以业务可比性为第一层、财务特征为第二层、数据可得性为第三层筛选。统一LTM/NTM、会计准则、非经常项和净债务口径，并解释为何剔除离群值。",
    "Start broad, then screen by business comparability, financial profile, and data availability. Normalize LTM/NTM periods, accounting standards, one-offs, and net debt, and explain excluded outliers.",
    ["可比公司", "Comps", "口径统一", "outlier"],
    "投行——估值与业务.docx", "金融方向/补充资料/辅导资料IPO/辅导资料/投行——估值与业务.docx"),
  make("ib-diligence-evidence-chain", "INVESTMENT_BANKING", "本地资料·IPO实务",
    "IPO尽调的证据链思维", "Evidence-chain thinking in IPO due diligence",
    "尽调结论需要由业务事实、合同单据、财务记录、访谈和外部查验相互印证，不能只依赖管理层陈述。",
    "Due-diligence conclusions should triangulate business facts, contracts, accounting records, interviews, and external checks rather than rely on management representations.",
    "围绕重大性和风险设计核查程序：提出假设、索取材料、交叉验证、记录差异、追踪闭环并形成可复核底稿。异常样本要扩样或升级。",
    "Design procedures around materiality and risk: form a hypothesis, request evidence, cross-check, record discrepancies, close open items, and retain reviewable workpapers. Expand or escalate anomalous samples.",
    ["IPO", "尽职调查", "证据链", "工作底稿"],
    "IPO实习的相关经历准备.docx", "金融方向/补充资料/辅导资料IPO/辅导资料/IPO实习的相关经历准备.docx"),
  make("ib-funding-gap", "INVESTMENT_BANKING", "本地资料·再融资",
    "再融资资金缺口测算", "Funding-gap calculation for follow-on financing",
    "资金缺口应基于业务计划、营运资金、资本开支、现有货币资金和可用融资能力动态测算。",
    "A funding gap should be modeled dynamically from the business plan, working capital, capex, available cash, and existing financing capacity.",
    "区分最低现金储备和真正可动用资金；对收入、周转率、付款周期、资本开支和债务到期设置基准及压力情景，并避免把募投项目需求与日常营运需求重复计算。",
    "Separate minimum cash buffers from deployable cash. Stress revenue, turnover, payment cycles, capex, and debt maturities, avoiding double counting between project funding and ordinary working-capital needs.",
    ["再融资", "资金缺口", "营运资金", "stress case"],
    "资金缺口的计算逻辑.docx", "金融方向/补充资料/辅导资料IPO/辅导资料/再融资业务/资金缺口的计算逻辑.docx"),
  make("ib-three-statement-interview", "INVESTMENT_BANKING", "本地资料·投行面试",
    "三表勾稽的面试讲法", "How to explain three-statement linkage in interviews",
    "从一项经营或融资变化出发，依次说明利润表、现金流量表和资产负债表的变化，并检查资产负债平衡。",
    "Start from one operating or financing change, walk through the income statement, cash-flow statement, and balance sheet, then confirm the balance sheet balances.",
    "使用税后影响，区分现金与非现金项目；明确期初期末关系，最后检查现金、留存收益、债务和固定资产等关键账户。",
    "Use after-tax effects and distinguish cash from non-cash items. Track opening-to-closing balances and verify cash, retained earnings, debt, and fixed assets.",
    ["三表勾稽", "会计", "three statements"],
    "面试知识库_KNOWLEDGE_BASE.md", "金融方向/面试知识库_KNOWLEDGE_BASE.md"),

  make("agent-four-components", "AI_PRODUCT_MANAGER", "本地资料·Agent方法论",
    "Agent的四个核心组件", "Four core components of an agent",
    "一个可用Agent需要模型、工具、记忆/状态和编排策略共同工作，而不是只有一个长Prompt。",
    "A usable agent combines a model, tools, memory/state, and orchestration rather than relying on a long prompt alone.",
    "模型负责理解与推理，工具连接外部能力，状态保存任务进度和证据，编排定义步骤、路由、终止与恢复。产品设计需逐项说明权限和失败模式。",
    "The model reasons, tools connect external capabilities, state preserves progress and evidence, and orchestration defines steps, routing, termination, and recovery. Product design should specify permissions and failures for each.",
    ["Agent", "tools", "memory", "orchestration"],
    "如何制作一个好的Agent_完整Workstream.md", "互联网方向/如何制作一个好的Agent_完整Workstream.md"),
  make("agent-five-phase-workstream", "AI_PRODUCT_MANAGER", "本地资料·Agent方法论",
    "从0到1构建Agent的五阶段工作流", "Five-phase workflow for building an agent",
    "完整流程包括需求与边界、架构、开发、评测迭代以及部署运维，每一阶段都有明确产物和退出条件。",
    "The lifecycle covers scope, architecture, implementation, evaluation/iteration, and deployment/operations, each with explicit artifacts and exit criteria.",
    "先定义用户任务、成功指标和不可做事项；再设计工具、状态和路由；以最小闭环实现；用场景化评测和BadCase迭代；上线后监控质量、成本、延迟与安全。",
    "Define user jobs, success metrics, and exclusions; design tools, state, and routing; implement the smallest loop; iterate through scenario evals and bad cases; then monitor quality, cost, latency, and safety.",
    ["Agent workflow", "scope", "evaluation", "deployment"],
    "如何制作一个好的Agent_完整Workstream.md", "互联网方向/如何制作一个好的Agent_完整Workstream.md"),
  make("agent-pattern-routing-reflection", "AI_PRODUCT_MANAGER", "本地资料·Agent方法论",
    "Agent设计模式：链式、路由、并行与反思", "Agent patterns: chaining, routing, parallelism, and reflection",
    "模式应由任务结构决定：稳定顺序用链式，不同意图用路由，独立子任务用并行，高质量产出用反思。",
    "Choose patterns from task structure: chaining for stable sequences, routing for intents, parallelism for independent work, and reflection for quality-sensitive output.",
    "不要为了Agent化而增加循环。每个模式都要设置最大步骤、终止条件、超时和降级路径，避免成本失控与无限自我修正。",
    "Do not add loops merely to appear agentic. Set maximum steps, stop conditions, timeouts, and fallbacks to avoid runaway cost and endless self-correction.",
    ["prompt chaining", "routing", "parallelization", "reflection"],
    "如何制作一个好的Agent_完整Workstream.md", "互联网方向/如何制作一个好的Agent_完整Workstream.md"),
  make("eval-consistency-calibration", "AI_PRODUCT_MANAGER", "本地资料·AI评测",
    "评测Agent一致性校准", "Calibrating evaluator-agent consistency",
    "低一致率往往来自指标定义模糊、证据不足、尺度漂移或不同维度相互重叠，不能只靠更换模型解决。",
    "Low evaluator agreement often comes from ambiguous criteria, weak evidence, scale drift, or overlapping dimensions, not merely from model choice.",
    "逐维度分析混淆样本，重写可观察的评分锚点，增加正反例和边界例，要求输出证据位置；对版本运行同一冻结集并同时看一致率、召回和人工复核。",
    "Analyze confused samples by dimension, rewrite observable anchors, add positive, negative, and boundary examples, and require evidence locations. Compare versions on a frozen set using agreement, recall, and human review.",
    ["评测一致性", "rubric", "calibration", "evidence"],
    "Agent迭代说明.md", "互联网方向/百度实习/Week 2/Agent迭代说明.md"),
  make("eval-batch-streaming", "AI_PRODUCT_MANAGER", "本地资料·AI评测",
    "批量评分与流式反馈", "Batch scoring and streaming feedback",
    "批量评分提高吞吐并降低重复开销，流式反馈改善等待体验，但两者要保持任务隔离、顺序标识和失败重试。",
    "Batch scoring improves throughput and amortizes overhead; streaming improves perceived latency, but both require task isolation, ordering identifiers, and retry handling.",
    "批量接口需限定大小并记录单项状态；SSE应发送阶段事件、心跳、错误和完成信号。质量评测不能因并发而共享可变上下文。",
    "Limit batch size and retain per-item status. SSE should emit stage events, heartbeats, errors, and completion. Concurrent evaluations must not share mutable context.",
    ["batch scoring", "SSE", "吞吐", "streaming"],
    "Agent迭代说明.md", "互联网方向/百度实习/Week 2/Agent迭代说明.md"),
  make("coding-agent-data-pipeline", "AI_PRODUCT_MANAGER", "本地资料·数据集",
    "AI Coding Agent训练数据管线", "Training-data pipeline for AI coding agents",
    "数据管线由素材采集标准化、PRD合成、执行轨迹合成、质量筛选和训练出口构成。",
    "The pipeline consists of source collection and normalization, PRD synthesis, trajectory synthesis, quality filtering, and training outputs.",
    "每个样本需保留来源、任务规格、环境、操作轨迹、最终产物、验证结果和失败原因。训练前执行去重、隐私与许可证检查，并按任务族而非随机行切分。",
    "Each sample should retain provenance, task specification, environment, action trace, final artifact, validation result, and failure reason. Before training, deduplicate, check privacy/licenses, and split by task family rather than random rows.",
    ["coding agent", "训练数据", "trajectory", "PRD synthesis"],
    "AI Coding Agent 训练数据管线方案总结.md", "互联网方向/百度实习/Week 3/AI Coding Agent 训练数据管线方案总结.md"),
  make("dataset-quality-gates", "AI_PRODUCT_MANAGER", "本地资料·数据集",
    "训练数据质量闸门", "Quality gates for training data",
    "数据质量不能只看格式完整，还要验证任务可执行、轨迹合理、结果正确、难度分布和来源合规。",
    "Data quality goes beyond formatting: tasks must be executable, trajectories sensible, outcomes correct, difficulty balanced, and provenance compliant.",
    "建议设置结构校验、自动运行、Rubric评分、异常检测和人工抽检五层闸门；失败样本不直接删除，而应标注失败类型供偏好或修复训练使用。",
    "Use structural validation, execution, rubric scoring, anomaly detection, and human sampling. Do not simply discard failures; label failure types for preference or repair training.",
    ["data quality", "quality gate", "人工抽检", "dataset"],
    "AI Coding Agent 训练数据管线方案总结.md", "互联网方向/百度实习/Week 3/AI Coding Agent 训练数据管线方案总结.md"),
  make("webdev-rubric", "AI_PRODUCT_MANAGER", "本地资料·AI评测",
    "Web开发产物的多维Rubric", "A multidimensional rubric for web-development artifacts",
    "Web评测应同时覆盖需求意图、功能正确性、布局、视觉规范、交互、动画和整体体验，并减少维度重叠。",
    "Web evaluation should cover intent alignment, functional correctness, layout, visual standards, interaction, motion, and overall experience while minimizing overlap.",
    "每个维度使用可观察行为和证据锚点，区分硬性错误与审美判断；报告既给总分，也展示维度置信度、失败截图或DOM证据。",
    "Use observable behaviors and evidence anchors per dimension, separating hard errors from aesthetic judgment. Reports should include totals, dimensional confidence, and screenshot or DOM evidence.",
    ["web evaluation", "rubric", "UI", "functional correctness"],
    "Week 1-3 项目总结.md", "互联网方向/百度实习/Week 1-3 项目总结.md"),
  make("badcase-closed-loop", "AI_PRODUCT_MANAGER", "本地资料·AI评测",
    "BadCase闭环：发现、归因、修复、回归", "Bad-case loop: detect, attribute, fix, regress",
    "BadCase管理的目标不是收集错误截图，而是形成可复现输入、根因标签、修复层级和防回归用例。",
    "Bad-case management should produce reproducible inputs, root-cause labels, fix layers, and regression tests rather than a folder of screenshots.",
    "按数据、Prompt、检索、工具、模型、后处理和体验分层归因；优先修复高频高损害问题，将代表样本加入冻结集并观察修复是否伤害其他切片。",
    "Attribute failures across data, prompt, retrieval, tools, model, post-processing, and UX. Prioritize frequent high-impact cases, add representatives to a frozen set, and check cross-slice regressions.",
    ["BadCase", "root cause", "regression", "frozen set"],
    "Week 1-3 项目总结.md", "互联网方向/百度实习/Week 1-3 项目总结.md"),
  make("ai-project-eight-stage-story", "AI_PRODUCT_MANAGER", "本地资料·面试表达",
    "AI项目复盘八段式", "Eight-stage AI project retrospective",
    "完整项目故事依次覆盖Hook、Why、What、How、Eval、Hard Problem、Result和下一版/复盘。",
    "A complete AI-project story covers Hook, Why, What, How, Eval, Hard Problem, Result, and the next iteration/lessons.",
    "Eval和Hard Problem是AI项目区别于普通产品项目的核心。每一段都要有事实或数据钩子，明确个人贡献，避免只讲功能清单。",
    "Eval and Hard Problem distinguish AI projects from ordinary product work. Each stage needs factual or numerical hooks, explicit personal ownership, and more than a feature list.",
    ["项目复盘", "AI PM interview", "Eval", "STAR"],
    "ai-pm-interview-coach_8stage_retrospective.md", "互联网方向/互联网产品/美团/ai-pm-interview-coach_8stage_retrospective.md"),
  make("project-v1-v2-story", "AI_PRODUCT_MANAGER", "本地资料·面试表达",
    "用V1到V2讲清产品迭代", "Explaining product iteration from V1 to V2",
    "V1讲目标、策略、功能和效果，V2必须由V1暴露的新机会或失败证据自然推出。",
    "V1 explains goal, strategy, features, and results; V2 should follow naturally from opportunities or failure evidence discovered in V1.",
    "避免把两个版本讲成并列功能。说明关键假设如何被验证、指标为何变化、什么反馈改变了优先级，以及新版本如何降低旧版本的风险。",
    "Do not present versions as parallel feature lists. Explain validated assumptions, metric changes, feedback-driven priorities, and how the new version reduces prior risks.",
    ["V1 V2", "产品迭代", "project retrospective"],
    "project-retrospective.md", "互联网方向/互联网产品/美团/project-retrospective.md"),
  make("coupon-agent-routing", "AI_PRODUCT_MANAGER", "本地资料·Agent案例",
    "优惠决策Agent的模块化链路", "A modular agent flow for promotion decisions",
    "复杂消费决策可拆为意图识别、实体与约束抽取、候选召回、规则计算、排序解释和追问澄清。",
    "A complex shopping decision can be decomposed into intent detection, entity/constraint extraction, candidate retrieval, rule calculation, ranking/explanation, and clarification.",
    "LLM负责理解模糊表达与生成解释，确定性金额计算交给规则或工具。每个模块输出结构化字段并保留来源，缺少关键约束时先追问而非猜测。",
    "Use the LLM for ambiguous language and explanations, while deterministic tools calculate money. Each module emits structured, sourced fields; ask for missing critical constraints instead of guessing.",
    ["优惠", "agent routing", "rules engine", "tool use"],
    "项目介绍_美团_agent链路.md", "互联网方向/AI产品面试准备/项目介绍_美团_agent链路.md"),
  make("llm-eval-five-steps", "AI_PRODUCT_MANAGER", "本地资料·AI评测",
    "LLM自动化评测集设计五步", "Five steps for designing an automated LLM eval set",
    "从任务与错误分类开始，采集真实和合成样本，建立标签规范，定义评分器，再通过人工校准和版本回归闭环。",
    "Start with task and error taxonomies, collect real and synthetic samples, establish labeling rules, define evaluators, then calibrate with humans and run version regressions.",
    "评测集需包含主路径、长尾、对抗和拒答样本；生成样本不能替代真实流量。保存模型、Prompt、知识库和评分器版本以保证结果可复现。",
    "Cover happy paths, long tails, adversarial cases, and abstention. Synthetic samples do not replace real traffic. Version the model, prompt, knowledge base, and evaluator for reproducibility.",
    ["LLM eval", "自动化评测", "golden set", "版本回归"],
    "项目介绍_智谱_STAR_2分钟.md", "互联网方向/AI产品面试准备/项目介绍_智谱_STAR_2分钟.md"),
  make("prompt-iteration-three-steps", "AI_PRODUCT_MANAGER", "本地资料·Prompt工程",
    "Prompt迭代的三步方法", "A three-step prompt-iteration method",
    "先从BadCase定位失败类型，再做最小Prompt改动，最后在冻结评测集和关键切片上验证收益与副作用。",
    "First classify failures from bad cases, then make the smallest prompt change, and finally validate benefits and side effects on a frozen eval set and critical slices.",
    "不要同时改角色、上下文、示例和输出格式，否则无法归因。优先使用结构化输出、明确边界、少量高质量示例和失败时的降级指令。",
    "Do not simultaneously change role, context, examples, and output format because attribution becomes impossible. Prefer structured output, clear boundaries, a few strong examples, and fallback instructions.",
    ["Prompt迭代", "BadCase", "ablation", "few-shot"],
    "项目介绍_智谱_STAR_2分钟.md", "互联网方向/AI产品面试准备/项目介绍_智谱_STAR_2分钟.md"),
  make("prd-review-questions", "AI_PRODUCT_MANAGER", "本地资料·产品方法",
    "AI PRD评审的关键问题", "Key questions in an AI PRD review",
    "AI PRD除用户价值与流程外，还必须明确模型职责、工具边界、数据来源、评测标准、失败体验和上线监控。",
    "Beyond user value and flows, an AI PRD must specify model responsibilities, tool boundaries, data provenance, evaluation criteria, failure UX, and production monitoring.",
    "评审时追问：不用AI是否更简单；正确答案如何定义；低置信时怎么办；谁能修改结果；哪些数据可发送给模型；成本与延迟预算是多少。",
    "Ask whether a non-AI solution is simpler, how correctness is defined, what happens at low confidence, who can override output, which data may reach the model, and the cost/latency budget.",
    ["AI PRD", "评审", "failure UX", "model boundary"],
    "美团问小团_找优惠_评审笔记_v2.docx", "互联网方向/互联网产品/美团问小团_找优惠_评审笔记_v2.docx")
];
